baseURL: https://iri-jwj.github.io/
languageCode: en-us
title: jwj's blog.
publishDir: docs
theme: cupper-hugo-theme

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: It's about Android Framework and what I want to write
  homeMetaContent: what's this
  footer: Powered by ash. and litte flower
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: true
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
#    - name: About
#      url: /about/
#      weight: 4
#    - name: RSS
#      url: /index.xml
#     weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2